# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
DATABASE:
  URL: ${DATABASE_URL}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  URL: ${CLOUDINARY_URL}
SUGGESTED_FOLLOWS:
  -
    id: 17d09e50-7bb2-4997-af06-9fd63edadc09 # Matt Massey
  -
    id: 429064f1-ef68-4f50-bcb5-63a2034f83ba # JR Cifani
  -
    id: dff317e2-c3db-4a40-9c8e-4b497810a0a1 # Beth Guckenberger
  -
    id: 7d25bc57-b6c2-436c-bfa5-7854091efad9 # Raúl Latoni
  -
    id: c4b7318e-64ab-4911-8a95-cabeb7156989 # Clay Harrington

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [2054]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [2055]
    MediaContentItem:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [2056, 2057]
    WeekendContentItem:
      EntityType: ContentChannelItem
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 210

  ALL_CONTENT_CHANNELS:
    - 3 # Stories & Blog
    - 5 # Church Header Links
    - 6 # Home Page: Ministries Grid
    - 8 # Home Page: Featured Grid
    - 2021 # Healing Center: Featured Grid
    - 2054 # Be Ready Series
    - 2055 # Be Ready Messages
    - 2056 # Get Set Challenges
    - 2057 # Service Opportunities
    - 2060 # Go Serve Mission

  SERMON_CHANNEL_ID: 5

TABS:
  HOME:
    - algorithms:
      - type: SERIES_ITEM_IN_PROGRESS
        arguments:
          categoryId: 8edb84c2-063a-45bf-b92e-845745edb57a
          limit: 1
          subtitle: Be Ready
          hasImage: false
      type: VerticalCardList
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 1acff1cb-805b-4561-b5f7-ee136b0b39b4
          limit: 1
          subtitle: Get Set
      type: VerticalCardList
    - algorithms:
      - type: OPEN_GO_TAB
        arguments:
          channelIds:
            - 2060
          limit: 1
          subtitle: Go Serve
      type: VerticalCardList
    - algorithms: [DAILY_PRAYER]
      isCard: true
      type: PrayerList
      title: Pray For Others

  READ: # Ready
    - algorithms:
      - type: SERIES_ITEM_IN_PROGRESS
        arguments:
          channelIds:
            - 2055
          limit: 1
          categoryId: 8edb84c2-063a-45bf-b92e-845745edb57a
      type: VerticalCardList
    - algorithms:
        - type: SORTED_CONTENT_FEED
          arguments:
            channelIds:
              - 2054
            limit: 6
      type: HorizontalCardList
      primaryAction:
        action: OPEN_CHANNEL
        title: 'Read More'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:20e2ef52-00e4-4530-864f-c3b7d67d6438
          title: All Series
      subtitle: All Series

  WATCH: # Set
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 1acff1cb-805b-4561-b5f7-ee136b0b39b4
          limit: 1
          subtitle: Get Set
      type: VerticalCardList
      subtitle: Daily Challenge
    - algorithms:
      - type: COMPLETED_CONTENT_FEED
        arguments:
          channelId: 1acff1cb-805b-4561-b5f7-ee136b0b39b4
      type: HorizontalCardList
      subtitle: Your Completed Challenges

  PRAY: # Go
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 2057
      type: VerticalCardList

  STORIES:
    contentItemId: UniversalContentItem:d1269b60-06c9-497e-8ad9-7f0cab5941bc
