# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
DATABASE:
  URL: ${DATABASE_URL}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  URL: ${CLOUDINARY_URL}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [2054]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [2055]
    MediaContentItem:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [2056, 2057]
    WeekendContentItem:
      EntityType: ContentChannelItem
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 210

  ALL_CONTENT_CHANNELS:
    - 3 # Stories & Blog
    - 5 # Church Header Links
    - 6 # Home Page: Ministries Grid
    - 8 # Home Page: Featured Grid
    - 2021 # Healing Center: Featured Grid
    - 2054 # Be Ready Series
    - 2055 # Be Ready Messages
    - 2056 # Get Set Challenges
    - 2057 # Service Opportunities
    - 2060 # Go Serve Mission

  SERMON_CHANNEL_ID: 5

TABS:
  HOME:
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2055
          limit: 1
          subtitle: Be Ready
          hasImage: false
      type: HeroList
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2056
          limit: 1
          subtitle: Get Set
      type: HeroList
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2060
          limit: 1
          subtitle: Go Serve
      type: HeroList
    - algorithms: [DAILY_PRAYER]
      isCard: true
      type: PrayerList
      title: Pray For Others

  READ: # Ready
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2055
      type: HeroList
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 2054
            limit: 3
      type: HorizontalCardList
      subtitle: Devotionals

  WATCH: # Set
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2056
          limit: 1
      type: HeroList
      subtitle: Daily Challenge
    - algorithms:
      - type: COMPLETED_CONTENT_FEED
        arguments:
          channelId: 1acff1cb-805b-4561-b5f7-ee136b0b39b4
      type: HorizontalCardList
      subtitle: Your Completed Challenges

  PRAY: # Go
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 2057
      type: VerticalCardList

  # STORIES:
  #   - algorithms:
  #       - type: CONTENT_FEED
  #         arguments:
  #           channelIds:
  #             - 8
  #           limit: 4
  #     type: VerticalCardList
  #     subtitle: Something Else
